#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index.html

# testing nginx configurations
sudo nginx -t

# Nginx where it should be listening on port 80

# Restarting nginx
sudo service nginx restart

# Reloading nginx
sudo service nginx reload
